// tslint:disable: object-literal-sort-keys
// tslint:disable: max-file-line-count

export const squirrelStatsGCSFileObj = {
  domain: null,
  _events: {},
  _eventsCount: 0,
  metadata: {
    kind: 'storage#object',
    id: 'squirrel-chasing/captured-squirrels/march-2020-stats.csv/12312012',
    selfLink:
      'https://www.googleapis.com/storage/v1/b/squirrel-chasing/o/captured-squirrels%2Fmarch-2020-stats.csv',
    mediaLink:
      'https://www.googleapis.com/download/storage/v1/b/squirrel-chasing/o/captured-squirrels%2Fmarch-2020-stats.csv?generation=12312012&alt=media',
    name: 'captured-squirrels/march-2020-stats.csv',
    bucket: 'squirrel-chasing',
    generation: '12312012',
    metageneration: '1',
    contentType: 'text/csv',
    storageClass: 'STANDARD',
    size: '112112',
    md5Hash: 'DOX0leRinotMTM7EGGXpjQ==',
    crc32c: 'fVcyCg==',
    etag: 'CI/UrJz0wugCEAE=',
    timeCreated: '2020-03-30T19:14:44.694Z',
    updated: '2020-03-30T19:14:44.694Z',
    timeStorageClassUpdated: '2020-03-30T19:14:44.694Z',
  },
  baseUrl: '/o',
  parent: {
    domain: null,
    _events: {},
    _eventsCount: 0,
    metadata: {},
    baseUrl: '/b',
    parent: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    id: 'squirrel-chasing',
    methods: {
      create: true,
    },
    interceptors: [],
    name: 'squirrel-chasing',
    storage: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    acl: {
      owners: {},
      readers: {},
      writers: {},
      pathPrefix: '/acl',
      default: {
        owners: {},
        readers: {},
        writers: {},
        pathPrefix: '/defaultObjectAcl',
      },
    },
    iam: {
      resourceId_: 'buckets/[object Promise]',
    },
  },
  id: 'captured-squirrels%2Fmarch-2020-stats.csv',
  methods: {},
  interceptors: [],
  bucket: {
    domain: null,
    _events: {},
    _eventsCount: 0,
    metadata: {},
    baseUrl: '/b',
    parent: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    id: 'squirrel-chasing',
    methods: {
      create: true,
    },
    interceptors: [],
    name: 'squirrel-chasing',
    storage: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    acl: {
      owners: {},
      readers: {},
      writers: {},
      pathPrefix: '/acl',
      default: {
        owners: {},
        readers: {},
        writers: {},
        pathPrefix: '/defaultObjectAcl',
      },
    },
    iam: {
      resourceId_: 'buckets/[object Promise]',
    },
  },
  storage: {
    baseUrl: 'https://www.googleapis.com/storage/v1',
    globalInterceptors: [],
    interceptors: [],
    packageJson: {
      name: '@google-cloud/storage',
      description: 'Cloud Storage Client Library for Node.js',
      version: '2.3.4',
      license: 'Apache-2.0',
      author: 'Google Inc.',
      engines: {
        node: '>=6.0.0',
      },
      repository: 'googleapis/nodejs-storage',
      main: './build/src/index.js',
      types: './build/src/index.d.ts',
      files: [
        'build/src',
        '!build/src/**/*.map',
        'AUTHORS',
        'CONTRIBUTORS',
        'COPYING',
      ],
      keywords: [
        'google apis client',
        'google api client',
        'google apis',
        'google api',
        'google',
        'google cloud platform',
        'google cloud',
        'cloud',
        'google storage',
        'storage',
      ],
      scripts: {
        docs: 'jsdoc -c .jsdoc.js',
        'generate-scaffolding':
          'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
        'system-test': 'mocha build/system-test --timeout 600000',
        'presystem-test': 'npm run compile',
        test: 'nyc mocha build/test',
        pretest: 'npm run compile',
        lint: 'eslint samples/ && gts check',
        'samples-test':
          'npm link && cd samples/ && npm link ../ && npm test && cd ../',
        'all-test': 'npm test && npm run system-test && npm run samples-test',
        check: 'gts check',
        clean: 'gts clean',
        compile: 'tsc -p .',
        fix: "gts fix && eslint --fix '**/*.js'",
        prepare: 'npm run compile',
      },
      dependencies: {
        '@google-cloud/common': '^0.27.0',
        '@google-cloud/paginator': '^0.1.0',
        '@google-cloud/promisify': '^0.3.0',
        arrify: '^1.0.0',
        async: '^2.0.1',
        compressible: '^2.0.12',
        'concat-stream': '^1.5.0',
        duplexify: '^3.5.0',
        extend: '^3.0.0',
        'gcs-resumable-upload': '^0.13.0',
        'hash-stream-validation': '^0.2.1',
        mime: '^2.2.0',
        'mime-types': '^2.0.8',
        once: '^1.3.1',
        pumpify: '^1.5.1',
        snakeize: '^0.1.0',
        'stream-events': '^1.0.1',
        'teeny-request': '^3.11.3',
        through2: '^3.0.0',
        'xdg-basedir': '^3.0.0',
      },
      devDependencies: {
        '@google-cloud/nodejs-repo-tools': '^3.0.0',
        '@google-cloud/pubsub': '^0.22.0',
        '@types/arrify': '^1.0.4',
        '@types/async': '^2.0.49',
        '@types/compressible': '^2.0.0',
        '@types/concat-stream': '^1.6.0',
        '@types/configstore': '^4.0.0',
        '@types/extend': '^3.0.0',
        '@types/mime': '^2.0.0',
        '@types/mime-types': '^2.1.0',
        '@types/mocha': '^5.2.3',
        '@types/nock': '^9.3.0',
        '@types/node-fetch': '^2.1.3',
        '@types/once': '^1.4.0',
        '@types/proxyquire': '^1.3.28',
        '@types/pumpify': '^1.4.1',
        '@types/request': '^2.47.1',
        '@types/through2': '^2.0.33',
        '@types/tmp': '0.0.33',
        '@types/uuid': '^3.4.4',
        '@types/xdg-basedir': '^2.0.0',
        codecov: '^3.0.0',
        eslint: '^5.0.0',
        'eslint-config-prettier': '^3.0.0',
        'eslint-plugin-node': '^8.0.0',
        'eslint-plugin-prettier': '^3.0.0',
        gts: '^0.9.0',
        'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
        'intelli-espower-loader': '^1.0.1',
        jsdoc: '^3.5.4',
        mocha: '^5.0.0',
        nock: '^10.0.1',
        'node-fetch': '^2.2.0',
        'normalize-newline': '^3.0.0',
        nyc: '^13.0.0',
        'power-assert': '^1.4.4',
        prettier: '^1.7.0',
        proxyquire: '^2.0.0',
        'source-map-support': '^0.5.6',
        tmp: '^0.0.33',
        typescript: '~3.1.1',
        uuid: '^3.1.0',
      },
    },
    projectId: 'o-u-t-s-i-d-e',
    projectIdRequired: false,
    authClient: {
      jsonContent: {
        client_email: 'mighty_huntress@dogs.com',
        private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
      },
      cachedCredential: {
        domain: null,
        _events: {},
        _eventsCount: 0,
        transporter: {},
        credentials: {
          access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
          token_type: 'Bearer',
          expiry_date: 1585600265000,
          refresh_token: 'jwt-placeholder',
        },
        certificateExpiry: null,
        refreshTokenPromises: {},
        eagerRefreshThresholdMillis: 300000,
        email: 'mighty_huntress@dogs.com',
        key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
        gtoken: {
          token: 'IaMaGoOdDoGpLeAsElEtMeIn',
          expiresAt: 1585600265000,
          rawToken: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expires_in: 3599,
            token_type: 'Bearer',
          },
          tokenExpires: null,
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          iss: 'mighty_huntress@dogs.com',
          scope:
            'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
        },
      },
      _cachedProjectId: 'o-u-t-s-i-d-e',
      scopes: [
        'https://www.googleapis.com/auth/iam',
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/devstorage.full_control',
      ],
    },
    acl: {
      OWNER_ROLE: 'OWNER',
      READER_ROLE: 'READER',
      WRITER_ROLE: 'WRITER',
    },
  },
  name: 'captured-squirrels/march-2020-stats.csv',
  acl: {
    owners: {},
    readers: {},
    writers: {},
    pathPrefix: '/acl',
  },
};

export const squirrelSimulatorGCSFileObj = {
  domain: null,
  _events: {},
  _eventsCount: 0,
  metadata: {
    kind: 'storage#object',
    id: 'squirrel-chasing/squirrel-simulator/bundle.js/11212012',
    selfLink:
      'https://www.googleapis.com/storage/v1/b/squirrel-chasing/o/squirrel-simulator%2Fbundle.js',
    mediaLink:
      'https://www.googleapis.com/download/storage/v1/b/squirrel-chasing/o/squirrel-simulator%2Fbundle.js?generation=11212012&alt=media',
    name: 'squirrel-simulator/bundle.js',
    bucket: 'squirrel-chasing',
    generation: '11212012',
    metageneration: '1',
    contentType: 'application/javascript',
    storageClass: 'STANDARD',
    size: '123112',
    md5Hash: 'DOX0leRinotMTM7EGGXpjQ==',
    crc32c: 'fVcyCg==',
    etag: 'CI/UrJz0wugCEAE=',
    timeCreated: '2020-03-30T19:14:44.694Z',
    updated: '2020-03-30T19:14:44.694Z',
    timeStorageClassUpdated: '2020-03-30T19:14:44.694Z',
  },
  baseUrl: '/o',
  parent: {
    domain: null,
    _events: {},
    _eventsCount: 0,
    metadata: {},
    baseUrl: '/b',
    parent: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    id: 'squirrel-chasing',
    methods: {
      create: true,
    },
    interceptors: [],
    name: 'squirrel-chasing',
    storage: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    acl: {
      owners: {},
      readers: {},
      writers: {},
      pathPrefix: '/acl',
      default: {
        owners: {},
        readers: {},
        writers: {},
        pathPrefix: '/defaultObjectAcl',
      },
    },
    iam: {
      resourceId_: 'buckets/[object Promise]',
    },
  },
  id: 'squirrel-simulator%2Fbundle.js',
  methods: {},
  interceptors: [],
  bucket: {
    domain: null,
    _events: {},
    _eventsCount: 0,
    metadata: {},
    baseUrl: '/b',
    parent: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    id: 'squirrel-chasing',
    methods: {
      create: true,
    },
    interceptors: [],
    name: 'squirrel-chasing',
    storage: {
      baseUrl: 'https://www.googleapis.com/storage/v1',
      globalInterceptors: [],
      interceptors: [],
      packageJson: {
        name: '@google-cloud/storage',
        description: 'Cloud Storage Client Library for Node.js',
        version: '2.3.4',
        license: 'Apache-2.0',
        author: 'Google Inc.',
        engines: {
          node: '>=6.0.0',
        },
        repository: 'googleapis/nodejs-storage',
        main: './build/src/index.js',
        types: './build/src/index.d.ts',
        files: [
          'build/src',
          '!build/src/**/*.map',
          'AUTHORS',
          'CONTRIBUTORS',
          'COPYING',
        ],
        keywords: [
          'google apis client',
          'google api client',
          'google apis',
          'google api',
          'google',
          'google cloud platform',
          'google cloud',
          'cloud',
          'google storage',
          'storage',
        ],
        scripts: {
          docs: 'jsdoc -c .jsdoc.js',
          'generate-scaffolding':
            'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
          'system-test': 'mocha build/system-test --timeout 600000',
          'presystem-test': 'npm run compile',
          test: 'nyc mocha build/test',
          pretest: 'npm run compile',
          lint: 'eslint samples/ && gts check',
          'samples-test':
            'npm link && cd samples/ && npm link ../ && npm test && cd ../',
          'all-test': 'npm test && npm run system-test && npm run samples-test',
          check: 'gts check',
          clean: 'gts clean',
          compile: 'tsc -p .',
          fix: "gts fix && eslint --fix '**/*.js'",
          prepare: 'npm run compile',
        },
        dependencies: {
          '@google-cloud/common': '^0.27.0',
          '@google-cloud/paginator': '^0.1.0',
          '@google-cloud/promisify': '^0.3.0',
          arrify: '^1.0.0',
          async: '^2.0.1',
          compressible: '^2.0.12',
          'concat-stream': '^1.5.0',
          duplexify: '^3.5.0',
          extend: '^3.0.0',
          'gcs-resumable-upload': '^0.13.0',
          'hash-stream-validation': '^0.2.1',
          mime: '^2.2.0',
          'mime-types': '^2.0.8',
          once: '^1.3.1',
          pumpify: '^1.5.1',
          snakeize: '^0.1.0',
          'stream-events': '^1.0.1',
          'teeny-request': '^3.11.3',
          through2: '^3.0.0',
          'xdg-basedir': '^3.0.0',
        },
        devDependencies: {
          '@google-cloud/nodejs-repo-tools': '^3.0.0',
          '@google-cloud/pubsub': '^0.22.0',
          '@types/arrify': '^1.0.4',
          '@types/async': '^2.0.49',
          '@types/compressible': '^2.0.0',
          '@types/concat-stream': '^1.6.0',
          '@types/configstore': '^4.0.0',
          '@types/extend': '^3.0.0',
          '@types/mime': '^2.0.0',
          '@types/mime-types': '^2.1.0',
          '@types/mocha': '^5.2.3',
          '@types/nock': '^9.3.0',
          '@types/node-fetch': '^2.1.3',
          '@types/once': '^1.4.0',
          '@types/proxyquire': '^1.3.28',
          '@types/pumpify': '^1.4.1',
          '@types/request': '^2.47.1',
          '@types/through2': '^2.0.33',
          '@types/tmp': '0.0.33',
          '@types/uuid': '^3.4.4',
          '@types/xdg-basedir': '^2.0.0',
          codecov: '^3.0.0',
          eslint: '^5.0.0',
          'eslint-config-prettier': '^3.0.0',
          'eslint-plugin-node': '^8.0.0',
          'eslint-plugin-prettier': '^3.0.0',
          gts: '^0.9.0',
          'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
          'intelli-espower-loader': '^1.0.1',
          jsdoc: '^3.5.4',
          mocha: '^5.0.0',
          nock: '^10.0.1',
          'node-fetch': '^2.2.0',
          'normalize-newline': '^3.0.0',
          nyc: '^13.0.0',
          'power-assert': '^1.4.4',
          prettier: '^1.7.0',
          proxyquire: '^2.0.0',
          'source-map-support': '^0.5.6',
          tmp: '^0.0.33',
          typescript: '~3.1.1',
          uuid: '^3.1.0',
        },
      },
      projectId: 'o-u-t-s-i-d-e',
      projectIdRequired: false,
      authClient: {
        jsonContent: {
          client_email: 'mighty_huntress@dogs.com',
          private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        },
        cachedCredential: {
          domain: null,
          _events: {},
          _eventsCount: 0,
          transporter: {},
          credentials: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            token_type: 'Bearer',
            expiry_date: 1585600265000,
            refresh_token: 'jwt-placeholder',
          },
          certificateExpiry: null,
          refreshTokenPromises: {},
          eagerRefreshThresholdMillis: 300000,
          email: 'mighty_huntress@dogs.com',
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          scopes: [
            'https://www.googleapis.com/auth/iam',
            'https://www.googleapis.com/auth/cloud-platform',
            'https://www.googleapis.com/auth/devstorage.full_control',
          ],
          gtoken: {
            token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expiresAt: 1585600265000,
            rawToken: {
              access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
              expires_in: 3599,
              token_type: 'Bearer',
            },
            tokenExpires: null,
            key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
            iss: 'mighty_huntress@dogs.com',
            scope:
              'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
          },
        },
        _cachedProjectId: 'o-u-t-s-i-d-e',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
      },
      acl: {
        OWNER_ROLE: 'OWNER',
        READER_ROLE: 'READER',
        WRITER_ROLE: 'WRITER',
      },
    },
    acl: {
      owners: {},
      readers: {},
      writers: {},
      pathPrefix: '/acl',
      default: {
        owners: {},
        readers: {},
        writers: {},
        pathPrefix: '/defaultObjectAcl',
      },
    },
    iam: {
      resourceId_: 'buckets/[object Promise]',
    },
  },
  storage: {
    baseUrl: 'https://www.googleapis.com/storage/v1',
    globalInterceptors: [],
    interceptors: [],
    packageJson: {
      name: '@google-cloud/storage',
      description: 'Cloud Storage Client Library for Node.js',
      version: '2.3.4',
      license: 'Apache-2.0',
      author: 'Google Inc.',
      engines: {
        node: '>=6.0.0',
      },
      repository: 'googleapis/nodejs-storage',
      main: './build/src/index.js',
      types: './build/src/index.d.ts',
      files: [
        'build/src',
        '!build/src/**/*.map',
        'AUTHORS',
        'CONTRIBUTORS',
        'COPYING',
      ],
      keywords: [
        'google apis client',
        'google api client',
        'google apis',
        'google api',
        'google',
        'google cloud platform',
        'google cloud',
        'cloud',
        'google storage',
        'storage',
      ],
      scripts: {
        docs: 'jsdoc -c .jsdoc.js',
        'generate-scaffolding':
          'repo-tools generate all && repo-tools generate lib_samples_readme -l samples/ --config ../.cloud-repo-tools.json',
        'system-test': 'mocha build/system-test --timeout 600000',
        'presystem-test': 'npm run compile',
        test: 'nyc mocha build/test',
        pretest: 'npm run compile',
        lint: 'eslint samples/ && gts check',
        'samples-test':
          'npm link && cd samples/ && npm link ../ && npm test && cd ../',
        'all-test': 'npm test && npm run system-test && npm run samples-test',
        check: 'gts check',
        clean: 'gts clean',
        compile: 'tsc -p .',
        fix: "gts fix && eslint --fix '**/*.js'",
        prepare: 'npm run compile',
      },
      dependencies: {
        '@google-cloud/common': '^0.27.0',
        '@google-cloud/paginator': '^0.1.0',
        '@google-cloud/promisify': '^0.3.0',
        arrify: '^1.0.0',
        async: '^2.0.1',
        compressible: '^2.0.12',
        'concat-stream': '^1.5.0',
        duplexify: '^3.5.0',
        extend: '^3.0.0',
        'gcs-resumable-upload': '^0.13.0',
        'hash-stream-validation': '^0.2.1',
        mime: '^2.2.0',
        'mime-types': '^2.0.8',
        once: '^1.3.1',
        pumpify: '^1.5.1',
        snakeize: '^0.1.0',
        'stream-events': '^1.0.1',
        'teeny-request': '^3.11.3',
        through2: '^3.0.0',
        'xdg-basedir': '^3.0.0',
      },
      devDependencies: {
        '@google-cloud/nodejs-repo-tools': '^3.0.0',
        '@google-cloud/pubsub': '^0.22.0',
        '@types/arrify': '^1.0.4',
        '@types/async': '^2.0.49',
        '@types/compressible': '^2.0.0',
        '@types/concat-stream': '^1.6.0',
        '@types/configstore': '^4.0.0',
        '@types/extend': '^3.0.0',
        '@types/mime': '^2.0.0',
        '@types/mime-types': '^2.1.0',
        '@types/mocha': '^5.2.3',
        '@types/nock': '^9.3.0',
        '@types/node-fetch': '^2.1.3',
        '@types/once': '^1.4.0',
        '@types/proxyquire': '^1.3.28',
        '@types/pumpify': '^1.4.1',
        '@types/request': '^2.47.1',
        '@types/through2': '^2.0.33',
        '@types/tmp': '0.0.33',
        '@types/uuid': '^3.4.4',
        '@types/xdg-basedir': '^2.0.0',
        codecov: '^3.0.0',
        eslint: '^5.0.0',
        'eslint-config-prettier': '^3.0.0',
        'eslint-plugin-node': '^8.0.0',
        'eslint-plugin-prettier': '^3.0.0',
        gts: '^0.9.0',
        'ink-docstrap': 'https://github.com/docstrap/docstrap/tarball/master',
        'intelli-espower-loader': '^1.0.1',
        jsdoc: '^3.5.4',
        mocha: '^5.0.0',
        nock: '^10.0.1',
        'node-fetch': '^2.2.0',
        'normalize-newline': '^3.0.0',
        nyc: '^13.0.0',
        'power-assert': '^1.4.4',
        prettier: '^1.7.0',
        proxyquire: '^2.0.0',
        'source-map-support': '^0.5.6',
        tmp: '^0.0.33',
        typescript: '~3.1.1',
        uuid: '^3.1.0',
      },
    },
    projectId: 'o-u-t-s-i-d-e',
    projectIdRequired: false,
    authClient: {
      jsonContent: {
        client_email: 'mighty_huntress@dogs.com',
        private_key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
      },
      cachedCredential: {
        domain: null,
        _events: {},
        _eventsCount: 0,
        transporter: {},
        credentials: {
          access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
          token_type: 'Bearer',
          expiry_date: 1585600265000,
          refresh_token: 'jwt-placeholder',
        },
        certificateExpiry: null,
        refreshTokenPromises: {},
        eagerRefreshThresholdMillis: 300000,
        email: 'mighty_huntress@dogs.com',
        key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
        scopes: [
          'https://www.googleapis.com/auth/iam',
          'https://www.googleapis.com/auth/cloud-platform',
          'https://www.googleapis.com/auth/devstorage.full_control',
        ],
        gtoken: {
          token: 'IaMaGoOdDoGpLeAsElEtMeIn',
          expiresAt: 1585600265000,
          rawToken: {
            access_token: 'IaMaGoOdDoGpLeAsElEtMeIn',
            expires_in: 3599,
            token_type: 'Bearer',
          },
          tokenExpires: null,
          key: 'DoGsArEgReAtSoMeSeCrEtStUfFhErE',
          iss: 'mighty_huntress@dogs.com',
          scope:
            'https://www.googleapis.com/auth/iam https://www.googleapis.com/auth/cloud-platform https://www.googleapis.com/auth/devstorage.full_control',
        },
      },
      _cachedProjectId: 'o-u-t-s-i-d-e',
      scopes: [
        'https://www.googleapis.com/auth/iam',
        'https://www.googleapis.com/auth/cloud-platform',
        'https://www.googleapis.com/auth/devstorage.full_control',
      ],
    },
    acl: {
      OWNER_ROLE: 'OWNER',
      READER_ROLE: 'READER',
      WRITER_ROLE: 'WRITER',
    },
  },
  name: 'squirrel-simulator/bundle.js',
  acl: {
    owners: {},
    readers: {},
    writers: {},
    pathPrefix: '/acl',
  },
};
